version: "3.1"
services:
  mongo:
    image: mongo:4
    container_name: mongo
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: userLanches
        MONGO_INITDB_ROOT_PASSWORD: passwordLanches
    ports:
      - 27017:27017